services:
  - type: web
    plan: free
    name: site-de-leilao
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn commerce.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --worker-tmp-dir /dev/shm --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: commerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: commerce-db
    plan: free
    databaseName: commerce
    user: commerce
