# Generated by Django 5.2.4 on 2026-03-13

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Cria categorias iniciais para a aba Categorias exibir algo."""
    Category = apps.get_model("auctions", "Category")
    defaults = [
        "Eletrônicos",
        "Moda",
        "Esportes",
        "Livros",
        "Casa e Cozinha",
        "Veículos",
        "Arte",
        "Outros",
    ]
    for name in defaults:
        Category.objects.get_or_create(name=name)


def remove_default_categories(apps, schema_editor):
    """Remove as categorias padrão ao fazer rollback (opcional)."""
    Category = apps.get_model("auctions", "Category")
    defaults = [
        "Eletrônicos",
        "Moda",
        "Esportes",
        "Livros",
        "Casa e Cozinha",
        "Veículos",
        "Arte",
        "Outros",
    ]
    Category.objects.filter(name__in=defaults).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_bid_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
